# Generated by Django 5.2 on 2025-04-20 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('fam', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('otc', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
            ],
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='connected_images',
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='perevalimages',
            name='img_old',
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='beauty_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='connect',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='level_autumn',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='level_spring',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='level_summer',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='level_winter',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='other_titles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='title',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perevalimages',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_api.perevalareas'),
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='images',
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='first_api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='images',
            field=models.ManyToManyField(to='first_api.perevalimages'),
        ),
    ]
