# Generated by Django 5.2 on 2025-04-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_api', '0002_user_remove_perevaladded_connected_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='level_autumn',
            field=models.CharField(blank=True, choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('1Б', '1Б'), ('2Б', '2Б'), ('3Б', '3Б')], max_length=10),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_spring',
            field=models.CharField(blank=True, choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('1Б', '1Б'), ('2Б', '2Б'), ('3Б', '3Б')], max_length=10),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_summer',
            field=models.CharField(blank=True, choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('1Б', '1Б'), ('2Б', '2Б'), ('3Б', '3Б')], max_length=10),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_winter',
            field=models.CharField(blank=True, choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('1Б', '1Б'), ('2Б', '2Б'), ('3Б', '3Б')], max_length=10),
        ),
    ]
